Feature/sensor threading
golechwierowicz/tin pull request #14
Opened 2017-05-30 08:29 UTC by rectified95

2017-05-30 19:38 UTC, marcin-sucharski requested changes

2017-05-30 19:38 UTC, marcin-sucharski commented on src/sensor/src/Sensor.cpp
> +        std::this_thread::sleep_for(std::chrono::seconds(2));
Albo zmień zakres lock-a na mutexie, albo wywal tego sleepa - w przeciwnym wypadku rozwalasz działania schedulera systemowego i wprowadzasz ciężkie do znalezienia bugi.

Dodatkowo nie rozumiem dlaczego jest tutaj sleep. Nie lepiej naraz wysłać do wszystkich dane, a potem odczekać 2 sekundy?

2017-05-30 19:38 UTC, marcin-sucharski commented on src/sensor/src/Sensor.cpp
> +            mutex.lock();
Zamiast lock/unlock lepiej używać `std::unique_lock<std::mutex> lock(mutex);`. Oprócz większej czytelności zabezpiecza przed przypadkowym niezwolnieniem mutexa oraz poprawnie obsługuje wyjątki.

2017-05-30 19:38 UTC, marcin-sucharski commented on src/sensor/src/Sensor.cpp
> +    mutex.lock();
j/w

2017-05-30 19:38 UTC, marcin-sucharski commented on src/sensor/src/Sensor.cpp
> +        auto addr = UdpConnection::get_address(config.cc_addr, config.cc_port);
Brakuje lock-a na dostęp do `config`.

2017-05-30 19:38 UTC, marcin-sucharski commented on src/sensor/src/Sensor.cpp
> +    config.cc_addr = cc_ip;
Ta metoda powinna zakładać locka na mutexa. Dzięki temu nie musisz tego powtarzać w każdym potencjalnym miejscu wywołania i nie robisz wymagań wobec kontekstu (których nie widać bez spojrzenia w kod). Dodatkowo wydaje się to bardziej naturalne (gwarancja atomowości operacji).

2017-05-30 19:38 UTC, marcin-sucharski commented on src/sensor/inc/Sensor.h
> +    void reload_config(std::string& cc_ip, in_port_t cc_port, std::vector<std::string>& central_ips);
Tutaj powinny być referencje do stałych obiektów (`const`). Alternatywnie po prostu obiekty (bo i tak kopiujesz dane, czyli można zrobić `move` i niech caller decyduje, czy chce skopiować, czy pozbyć się swojej instancji obiektu).

2017-05-30 21:42 UTC, marcin-sucharski approved these changes

2017-05-31 06:20 UTC, golechwierowicz approved these changes

2017-05-31 06:20 UTC, merged